version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "deps"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "deps"
    groups:
      actions:
        patterns:
          - "*"
