"""
Typed event stream — transforms raw decoded packets into semantic game events.
"""

from wows_replay_parser.events.models import (
    AchievementEvent,
    AirSupportEvent,
    CapContestEvent,
    CapturePointUpdateEvent,
    ChatEvent,
    ConsumableEvent,
    DamageEvent,
    DeathEvent,
    GameEvent,
    MinimapVisionEvent,
    PositionEvent,
    PotentialDamageEvent,
    PropertyUpdateEvent,
    RawEvent,
    RibbonEvent,
    ScoreUpdateEvent,
    ScoutingDamageEvent,
    ShotCreatedEvent,
    ShotDestroyedEvent,
    ShotEvent,
    SquadronEvent,
    TorpedoCreatedEvent,
)
from wows_replay_parser.events.stream import EventStream

__all__ = [
    "AchievementEvent",
    "AirSupportEvent",
    "CapContestEvent",
    "CapturePointUpdateEvent",
    "ChatEvent",
    "ConsumableEvent",
    "DamageEvent",
    "DeathEvent",
    "EventStream",
    "GameEvent",
    "MinimapVisionEvent",
    "PositionEvent",
    "PotentialDamageEvent",
    "PropertyUpdateEvent",
    "RawEvent",
    "RibbonEvent",
    "ScoreUpdateEvent",
    "ScoutingDamageEvent",
    "ShotCreatedEvent",
    "ShotDestroyedEvent",
    "ShotEvent",
    "SquadronEvent",
    "TorpedoCreatedEvent",
]
